/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twosigma_beaker_cpp_utils_CppKernel */

#ifndef _Included_com_twosigma_beaker_cpp_utils_CppKernel
#define _Included_com_twosigma_beaker_cpp_utils_CppKernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twosigma_beaker_cpp_utils_CppKernel
 * Method:    cInit
 * Signature: (Lcom/twosigma/beaker/NamespaceClient;)V
 */
JNIEXPORT void JNICALL Java_com_twosigma_beaker_cpp_utils_CppKernel_cInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_twosigma_beaker_cpp_utils_CppKernel
 * Method:    cLoad
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_twosigma_beaker_cpp_utils_CppKernel_cLoad
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_twosigma_beaker_cpp_utils_CppKernel
 * Method:    cLoadAndRun
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_twosigma_beaker_cpp_utils_CppKernel_cLoadAndRun
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
